# Base configs
baseurl: /profileflat

# UI configs
title: "Kathan Thaker"
author: "Kathan Thaker"
about: "A Coder|A BELIEVER|AN Enthusiast"
social_urls:
  facebook: "https://www.facebook.com/kathan102"
  twitter: "https://twitter.com/kathan_thaker"
  instagram: "https://www.instagram.com/kathan_thaker/"

theme: jekyll-theme-hacker