# Base configs
baseurl: /profileflat

# UI configs
title: "Udit Srivastava"
author: "Udit Srivastava"
about: "A Pythonista|Fond Of SQL"
social_urls:
  facebook: "https://www.facebook.com/shaitanudit.srivastava"
  twitter: "https://twitter.com/Udit9519"
  instagram: "https://www.instagram.com/udit_srivastav/"
